### ISSUE TITLE
macOS High Sierra rendering issue

### ISSUE THREAD

**Issue by LinusU** [LinusU/emoji-commit#6]
<img width="354" alt="screen shot 2017-08-01 at 16 36 35" src="https://user-images.githubusercontent.com/189580/28833562-9be1afe6-76d7-11e7-9d49-dd5bba2455f9.png">

I think that the problem is that I before assumed that every emoji would take up to chars, but only advance the cursor by one, so I always printed a space after each emoji. Behaviour should somehow be detected and then it should do the right thing...

**Comment by Offirmo** [comment]
FYI Unicode 9 introduced full/half width emojis, that feature may have landed in High Sierra. TL;DR. the extra space is no longer needed for emojis recognized as "wide".

**Comment by albinekb** [comment]
![image](https://user-images.githubusercontent.com/5027156/31664924-88d28086-b347-11e7-98bf-20b04854328a.png)

iTerm2: `Build 3.1.4.beta.1`
macOS High Sierra: `10.13.1 Beta (17B35a)`

**Comment by LinusU** [comment]
This works on latest macOS now, so closing this...

macOS `12.6 (21G115)`
Terminal `Version 2.12.7 (445)`
