### ISSUE TITLE
Option to add commit body text

### ISSUE THREAD

**Issue by albinekb** [LinusU/emoji-commit#7]
It would be nice if emoji-commit allowed you to add a commit body text too, the way I imagine it, after entering the short commit message, you'd press alt/shift+enter and open your `$EDITOR` on the correct line.

To open the editor on the correct line, we will need a separate rust lib to handle the different ways editors enable this, for example, [this](https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders) is how you do it i VS Code

**Comment by LinusU** [comment]
vim: https://stackoverflow.com/questions/3313418/starting-vim-at-a-certain-position-line-and-column-of-a-file
